global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sitemanager'
    static_configs:
      - targets: ['sitemanager:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
